const columnConfig = [
    { key: "tier",    label: "Tier",         width: "3%",    headingFontSize: "9px",  cellFontSize: "11px", textAlign: "center" },
    { key: "logo",    label: "Logo",         width: "4%",    headingFontSize: "9px",  textAlign: "center" },
    { key: "name",    label: "Service",      width: "12%",   headingFontSize: "9px",  cellFontSize: "16px", cellFontFamily: "'Times New Roman', Times, serif" },
    { key: "output",  label: "Output Type",  width: "5%",    headingFontSize: "9px",  cellFontSize: "11px", textAlign: "center" },
    { key: "free",    label: "Free",         width: "3.5%",  headingFontSize: "9px",  textAlign: "center" },
    { key: "credits", label: "Credits",      width: "3.5%",  headingFontSize: "9px",  textAlign: "center" },
    { key: "sub",     label: "Sub",          width: "3.5%",  headingFontSize: "9px",  textAlign: "center" },
    { key: "api",     label: "API",          width: "3.5%",  headingFontSize: "9px",  textAlign: "center" },
    { key: "local",   label: "Local",        width: "3.5%",  headingFontSize: "9px",  textAlign: "center" },
    { key: "nsfw",    label: "NSFW",         width: "3.5%",  headingFontSize: "9px",  textAlign: "center" },
    { key: "url",     label: "Domain",       width: "20%",   headingFontSize: "9px",  cellFontSize: "12px", cellFontFamily: "ui-monospace, monospace" },
    { key: "desc",    label: "Key Detail",   width: "30%",   headingFontSize: "9px",  cellFontSize: "11px" },
];

// ─── Speech & Narration ──────────────────────────────────────────────────────
const speechAndNarration = [
    {
            "name": "ElevenLabs",
            "url": "elevenlabs.io",
            "output": "MP3/WAV/API",
            "desc": "Industry standard for emotion-aware voice cloning.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Fish Audio",
            "url": "fish.audio",
            "output": "Weights/API",
            "desc": "Optimized for sub-second latency in conversational agents.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Kokoro-82M",
            "url": "huggingface.co",
            "output": "ONNX/Python",
            "desc": "Extremely small footprint; runs locally on CPUs.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 0,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Google Cloud TTS",
            "url": "cloud.google.com/text-to-speech",
            "output": "API (WAV/MP3)",
            "desc": "WaveNet voices; 50+ languages; 1M chars/month free.",
            "free": 0,
            "credits": 1,
            "sub": 0,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Amazon Polly",
            "url": "aws.amazon.com/polly",
            "output": "API (Speech Marks)",
            "desc": "Speech marks for animation sync; 5M chars free (first year).",
            "free": 0,
            "credits": 1,
            "sub": 0,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Azure TTS",
            "url": "azure.microsoft.com",
            "output": "API (Neural)",
            "desc": "140+ languages; Custom Neural Voice; enterprise security.",
            "free": 0,
            "credits": 1,
            "sub": 0,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Cartesia",
            "url": "cartesia.ai",
            "output": "API (Streaming)",
            "desc": "Ultra-low latency (40-90ms); emotional expression support.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Speechmatics",
            "url": "speechmatics.com",
            "output": "API",
            "desc": "Sub-150ms latency; unified STT+TTS; cost-effective.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Rime",
            "url": "rime.ai",
            "output": "API / On-prem",
            "desc": "Conversational prosody; sub-100ms; trained on real dialogue.",
            "free": 0,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Neuphonic",
            "url": "neuphonic.com",
            "output": "API / On-device",
            "desc": "On-device deployment; instant voice cloning; no GPU required.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Hume",
            "url": "hume.ai",
            "output": "API (EVI)",
            "desc": "Emotional intelligence; prompt-based emotional delivery.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "MiniMax",
            "url": "minimax.io",
            "output": "API",
            "desc": "Long-text mode (200k chars); 99% voice similarity cloning.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "OpenAI TTS",
            "url": "openai.com",
            "output": "API",
            "desc": "GPT-4 powered; style prompting; 6 preset voices.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "IBM Watson TTS",
            "url": "ibm.com/watson/tts",
            "output": "API / On-prem",
            "desc": "Offline deployment; custom word dictionaries; enterprise.",
            "free": 0,
            "credits": 1,
            "sub": 0,
            "api": 1,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Murf AI",
            "url": "murf.ai",
            "output": "MP3/WAV",
            "desc": "Script-to-speech with 120+ voices; built-in editor for timing and emphasis; ideal for audiobooks.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Play.ht",
            "url": "play.ht",
            "output": "MP3/WAV/API",
            "desc": "Advanced voice cloning; supports long-form narration; podcast and audiobook workflows.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Speechify",
            "url": "speechify.com",
            "output": "MP3/Audio",
            "desc": "Paste scripts or upload documents; high-quality narration; great for audiobook creation.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Resemble AI",
            "url": "resemble.ai",
            "output": "MP3/WAV/API",
            "desc": "Real-time voice cloning; script narration with emotional control; API integration.",
            "free": 0,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Lovo (Genny)",
            "url": "lovo.ai",
            "output": "MP3/WAV",
            "desc": "Specialized Genny tool for script narration; 500+ voices; emotion and pacing control.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "NaturalReader",
            "url": "naturalreaders.com",
            "output": "MP3/Audio",
            "desc": "Paste scripts for instant narration; 140+ voices; commercial licensing available.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "WellSaid Labs",
            "url": "wellsaidlabs.com",
            "output": "MP3/WAV",
            "desc": "Enterprise-grade narration; realistic avatars; script-to-audio workflows for training.",
            "free": 0,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Descript (Overdub)",
            "url": "descript.com",
            "output": "Audio/Video",
            "desc": "Script-based editing via text; clone your voice; type scripts for instant narration.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Fliki",
            "url": "fliki.ai",
            "output": "MP4/Audio",
            "desc": "Script-to-audio with AI voices; add stock visuals for video narration; 2000+ voices.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Listnr",
            "url": "listnr.tech",
            "output": "MP3/WAV",
            "desc": "Text-to-speech with 600+ voices; podcast and audiobook creation; voice cloning.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Narration Box (Formerly VoiceBuddy)",
            "url": "narrationbox.com",
            "output": "MP3",
            "desc": "Script narration with 400+ voices; commercial use; SSML support for fine control.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Clipchamp (Microsoft)",
            "url": "clipchamp.com",
            "output": "Video/Audio",
            "desc": "Built-in TTS for video narration; free tier; Azure-powered voices.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Coqui TTS",
            "url": "coqui.ai",
            "output": "Weights/API",
            "desc": "Open-source; train custom voice models; script narration via local deployment.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 1,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Bark (Suno)",
            "url": "github.com/suno-ai/bark",
            "output": "Audio",
            "desc": "Open-source multilingual TTS; supports music and sound effects in narration.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 0,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "OpenVoice",
            "url": "github.com/myshell-ai/OpenVoice",
            "desc": "Instant voice cloning; open-source; paste scripts for custom voice narration locally.",
            "output": "Audio",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 0,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Pictory",
            "url": "pictory.ai",
            "output": "MP4",
            "desc": "Script-to-video with AI voiceover; auto-captioning; stock media library.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "InVideo AI",
            "url": "invideo.io",
            "output": "MP4",
            "desc": "Paste scripts for full video narration; AI voiceover with stock footage automation.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        }
];

// ─── Image Analysis ───────────────────────────────────────────────────────────
const imageAnalysis = [
        {
            "name": "Claude 3.5 Sonnet",
            "url": "claude.ai",
            "output": "JSON/Text",
            "desc": "Best-in-class for extracting data from dense tables/charts.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "ChatGPT (GPT-4o)",
            "url": "chat.openai.com",
            "output": "Text / JSON",
            "desc": "Native multimodal; upload images for analysis, OCR, charts, diagrams.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Google Gemini (Vision)",
            "url": "gemini.google.com",
            "output": "Multi-modal",
            "desc": "Analyze images, charts, screenshots via chat; 2M token context for videos.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Microsoft Copilot (Vision)",
            "url": "copilot.microsoft.com",
            "output": "Text / JSON",
            "desc": "GPT-4 Vision powered; analyze screenshots, diagrams, photos via chat.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Gemini 2.5 Pro",
            "url": "aistudio.google.com",
            "output": "Multi-modal",
            "desc": "Supports 2M+ token context for processing long video files.",
            "free": 0,
            "credits": 1,
            "sub": 0,
            "api": 1,
            "local": 1,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "GPT-4o",
            "url": "openai.com",
            "output": "Text / JSON",
            "desc": "Native multimodal; strong OCR and diagram understanding.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Llama 3.2 Vision",
            "url": "meta.ai",
            "output": "Text",
            "desc": "Open-weights vision model; runs locally with sufficient VRAM.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 1,
            "local": 1,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Surya OCR",
            "url": "github.com/VikParuchuri/surya",
            "output": "Text / Layout",
            "desc": "Open-source OCR; 90+ languages; document layout analysis.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 0,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Tesseract 5",
            "url": "github.com/tesseract-ocr/tesseract",
            "output": "Text",
            "desc": "Classic open-source OCR engine; 100+ languages.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 0,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Google Cloud Vision",
            "url": "cloud.google.com/vision",
            "output": "JSON API",
            "desc": "OCR + object/face detection; 1k units/month free.",
            "free": 0,
            "credits": 1,
            "sub": 0,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Azure Computer Vision",
            "url": "azure.microsoft.com",
            "output": "JSON API",
            "desc": "Read API for OCR; handwritten text support; enterprise.",
            "free": 0,
            "credits": 1,
            "sub": 0,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "CLIP Interrogator",
            "url": "huggingface.co/spaces/philschmid/clip-interrogator",
            "output": "Text Prompt",
            "desc": "Specialized tool for reverse-engineering prompts from images using CLIP.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 0,
            "local": 1,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Img2Prompt",
            "url": "github.com/pharmapsychotic/clip-interrogator",
            "output": "Text Prompt",
            "desc": "Open-source CLIP-based image captioning for Stable Diffusion prompts.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 0,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Perplexity (Vision)",
            "url": "perplexity.ai",
            "output": "Text Prompt",
            "desc": "Upload images for analysis; get detailed descriptions and context.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "NotebookLM",
            "url": "notebooklm.google",
            "output": "Audio/Video/Text",
            "desc": "Converts documents, PDFs, and visuals into narrated podcast-style summaries.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Florence-2",
            "url": "huggingface.co/microsoft/Florence-2",
            "output": "JSON / Labels",
            "desc": "Lightweight open-source vision model for detection, captioning, and dense OCR.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 0,
            "local": 1,
            "nsfw": 0,
            "tier": 2,
        }
];

// ─── Text / Image to Video ────────────────────────────────────────────────────
const textImageToVideo = [
        {
            "name": "OpenAI Sora",
            "url": "openai.com",
            "output": "1080p / 60s",
            "desc": "Superior multi-character interaction and scene continuity; physics simulation; image-to-video with superior character consistency.",
            "free": 0,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Google Veo 2",
            "url": "deepmind.google",
            "output": "1080p/4K",
            "desc": "Image-to-video with cinematic understanding; native audio sync; deep YouTube integration; cinematic understanding.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Kling 1.5",
            "url": "klingai.com",
            "output": "MP4 / 120s",
            "desc": "Industry-leading duration up to 5 min; complex motion from images; prevents deformation in long clips.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Runway Gen-3 Alpha",
            "url": "runwayml.com",
            "output": "MP4 / 16s",
            "desc": "Motion brush; precise camera control; frame-by-frame editing; industry-leading cinematic quality.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Luma Dream Machine",
            "url": "lumalabs.ai",
            "output": "MP4 / 5s",
            "desc": "Keyframe control (start/end images); photorealistic results; fast generation; excellent free tier.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Pika 2.5",
            "url": "pika.art",
            "output": "MP4 / 4s",
            "desc": "PikaTwists effects; physics-based image animations; lip-sync support; user-friendly interface.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Haiper 2.0",
            "url": "haiper.ai",
            "output": "MP4 / 2-4s",
            "desc": "High-action transitions from images; blur/movement simulation; commercial transitions.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "LTX Studio",
            "url": "lightricks.com",
            "output": "MP4",
            "desc": "Image-to-sequence; multi-shot generation from single image; long-form script handling; consistent characters.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Leonardo Motion",
            "url": "leonardo.ai",
            "output": "MP4",
            "desc": "Cinemagraph-style animation; motion brushes for looping visuals; integrated with Leonardo.ai platform.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Vidu",
            "url": "vidu.studio",
            "output": "MP4",
            "desc": "Multi-camera from single image; consistent character animation; different angles from same scene.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Stable Video Diffusion",
            "url": "stability.ai",
            "output": "MP4 / Weights",
            "desc": "Open-source image-to-video; camera pan/tilt; local deployment; open model weights.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 1,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "CogVideoX",
            "url": "zhipuai.cn",
            "output": "MP4 / Weights",
            "desc": "Open-source; low VRAM; image-to-video consistency; 3D VAE-based; high text-to-video consistency.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 0,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "LTX 2.3",
            "url": "lightricks.com",
            "output": "MP4 / 4K",
            "desc": "Open-source 22B model; audio-video synthesis in single pass; 4K output support.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 0,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Open-Sora",
            "url": "github.com/hpcaitech/OpenSora",
            "output": "Weights",
            "desc": "Community Sora replica; image-to-video support; open-source; democratizing video generation.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 0,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Mochi 1",
            "url": "genmo.ai",
            "output": "Weights",
            "desc": "Open-weights video model; asymmetric diffusion; high-fidelity physics; local deployment.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 0,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Kaiber",
            "url": "kaiber.ai",
            "output": "MP4",
            "desc": "Music-reactive image animation; style transfer; artist-focused tools; creative workflows.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Immersity AI",
            "url": "immersity.ai",
            "output": "MP4 / 3D",
            "desc": "2D-to-3D conversion; depth-aware camera movement; legacy LeiaLOOBS; immersive experiences.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Seedance 2.0",
            "url": "seedance.io",
            "output": "MP4 / 1080p",
            "desc": "Affordable pricing from $9.99; HD quality; pay-as-you-go options; cost-effective.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "InVideo AI",
            "url": "invideo.io",
            "output": "MP4",
            "desc": "Script-to-video with stock footage; voice cloning; template library; automated editing.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Hailuo (MiniMax)",
            "url": "hailuo.ai",
            "output": "MP4 / 6s",
            "desc": "Exceptional human motion and physics simulation; allows high-action scenes.",
            "free": 1,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        }
];

// ─── Text to Image ────────────────────────────────────────────────────────────
const textToImage = [
        {
            "name": "Midjourney v7",
            "url": "midjourney.com",
            "output": "Web/Discord",
            "desc": "Requires Discord for main interaction; closed model ecosystem.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "ChatGPT (DALL-E 3)",
            "url": "chat.openai.com",
            "output": "Web Chat",
            "desc": "DALL-E 3 integrated into ChatGPT; conversational image generation with refinements.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Google Gemini (Imagen)",
            "url": "gemini.google.com",
            "output": "Web Chat",
            "desc": "Imagen 3 integrated into Gemini; generate images via natural conversation.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Microsoft Copilot (Designer)",
            "url": "copilot.microsoft.com",
            "output": "Web Chat",
            "desc": "DALL-E 3 powered image generation; free boosts daily; integrated in chat.",
            "free": 1,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Stable Diffusion XL",
            "url": "stability.ai",
            "output": "Weights (Safetensors)",
            "desc": "Full local control; compatible with Automatic1111/ComfyUI.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 1,
            "local": 1,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "DALL-E 3",
            "url": "openai.com",
            "output": "Web/API",
            "desc": "High prompt adherence via LLM integration; strong safety filters.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Flux.1 [dev]",
            "url": "blackforestlabs.ai",
            "output": "Weights",
            "desc": "High VRAM requirement for local; current state-of-the-art for anatomy.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 1,
            "local": 1,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Ideogram 2.0",
            "url": "ideogram.ai",
            "output": "Web/API",
            "desc": "Optimized for graphic design and reliable text rendering.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Adobe Firefly",
            "url": "firefly.adobe.com",
            "output": "Web/Plugin",
            "desc": "Trained on licensed assets only; native Photoshop integration.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Leonardo.ai",
            "url": "leonardo.ai",
            "output": "Web UI",
            "desc": "Web-based model management and fine-tuning storage.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Recraft.ai",
            "url": "recraft.ai",
            "output": "SVG / Raster",
            "desc": "Provides infinite-scale vector output for logo/brand design.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "DALL-E 2",
            "url": "openai.com",
            "output": "Web/API",
            "desc": "Earlier OpenAI model; simpler and faster for basic tasks.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Playground AI",
            "url": "playgroundai.com",
            "output": "Web UI",
            "desc": "Multi-model platform with SDXL, Flux; generous free tier.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "SeaArt",
            "url": "seaart.ai",
            "output": "Web UI",
            "desc": "Anime-focused with ControlNet support; community model sharing.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Tensor.art",
            "url": "tensor.art",
            "output": "Web UI",
            "desc": "Hosts community LoRAs and checkpoints; cloud-based generation.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Mage.space",
            "url": "mage.space",
            "output": "Web UI",
            "desc": "Clean interface with SDXL and custom model support.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Bing Image Creator",
            "url": "bing.com/images/create",
            "output": "Web",
            "desc": "Powered by DALL-E 3; free with Microsoft account.",
            "free": 0,
            "credits": 1,
            "sub": 0,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Pixlr",
            "url": "pixlr.com",
            "output": "Web UI",
            "desc": "Three quality modes (Fast/Pro/Ultra); negative prompts support.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Canva Magic Media",
            "url": "canva.com",
            "output": "Web UI",
            "desc": "50 free images; integrates directly into design canvas.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Fotor",
            "url": "fotor.com",
            "output": "Web UI",
            "desc": "Beginner-friendly with daily free credits via check-ins.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 4,
        },
        {
            "name": "Freepik AI",
            "url": "freepik.com",
            "output": "Web UI",
            "desc": "20 free images/day; commercial-safe licensed training data.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 4,
        },
        {
            "name": "DeepAI",
            "url": "deepai.org",
            "output": "Web/API",
            "desc": "Three quality tiers; full commercial rights; API integration.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 4,
        },
        {
            "name": "Renderforest",
            "url": "renderforest.com",
            "output": "Web UI",
            "desc": "All-in-one for images, logos, and videos from text.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 4,
        }
];

// ─── Text to Music ────────────────────────────────────────────────────────────
const textToMusic = [
        {
            "name": "Suno v4",
            "url": "suno.com",
            "output": "MP3/WAV",
            "desc": "Generates full songs with lyrics and multi-layered vocals.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Udio 2",
            "url": "udio.com",
            "output": "MP3/WAV",
            "desc": "Highest audio fidelity for complex musical genres.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Mubert",
            "url": "mubert.com",
            "output": "MP3 / WAV",
            "desc": "Royalty-free instrumental tracks; image-to-music; 5s-25min length.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Beatoven",
            "url": "beatoven.ai",
            "output": "MP3 / WAV",
            "desc": "Video-synced music; shapes intensity around video cuts.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "AIVA",
            "url": "aiva.ai",
            "output": "MIDI / WAV",
            "desc": "Cinematic/orchestral scores; tempo and intensity control.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Soundraw",
            "url": "soundraw.io",
            "output": "WAV",
            "desc": "Customizable AI music; adjust tempo, mood, and length.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Boomy",
            "url": "boomy.com",
            "output": "MP3",
            "desc": "Quick song creation; distributes to streaming platforms.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        }
];

// ─── Web Chat & Coding Agents ────────────────────────────────────────────────
const webChatAndCoding = [
        {
            "name": "ChatGPT",
            "url": "openai.com",
            "output": "Web Chat",
            "desc": "Industry-leading conversational AI with advanced reasoning and multimodal capabilities.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Claude",
            "url": "claude.ai",
            "output": "Web Chat",
            "desc": "Exceptional reasoning, coding, and writing capabilities with large context window.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Google Gemini",
            "url": "gemini.google.com",
            "output": "Web Chat",
            "desc": "Deep Google ecosystem integration with multimodal understanding.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Qwen",
            "url": "chat.qwen.ai",
            "output": "Web Chat",
            "desc": "Alibaba's advanced AI with strong coding, reasoning, and multilingual capabilities.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Microsoft Copilot",
            "url": "copilot.microsoft.com",
            "output": "Web Chat",
            "desc": "GPT-4 powered with web search and Microsoft 365 integration.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Perplexity",
            "url": "perplexity.ai",
            "output": "Web Chat",
            "desc": "AI-powered search engine with cited sources and real-time information.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Poe",
            "url": "poe.com",
            "output": "Web Chat",
            "desc": "Multi-bot platform with access to Claude, GPT-4, and specialized models.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Character.ai",
            "url": "character.ai",
            "output": "Web Chat",
            "desc": "Roleplay-focused chat with customizable AI personalities and characters.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "HuggingChat",
            "url": "huggingface.co",
            "output": "Web Chat",
            "desc": "Open-source chat interface with access to various open models.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Grok",
            "url": "x.ai",
            "output": "Web Chat",
            "desc": "Real-time information access with X/Twitter integration and witty personality.",
            "free": 0,
            "credits": 0,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "YouChat",
            "url": "you.com",
            "output": "Web Chat",
            "desc": "AI search assistant with real-time web results and app integrations.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Phind",
            "url": "phind.com",
            "output": "Web Chat",
            "desc": "Developer-focused AI search engine with code examples and technical answers.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Mistral Le Chat",
            "url": "chat.mistral.ai",
            "output": "Web Chat",
            "desc": "European AI with efficient models and strong reasoning capabilities.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "DeepSeek V4",
            "url": "deepseek.ai",
            "output": "Web Chat",
            "desc": "Ultra-efficient frontier model with 1M context window and minimal censorship.",
            "free": 1,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 1,
            "tier": 1,
        },
        {
            "name": "Inflection Pi",
            "url": "pi.ai",
            "output": "Web Chat",
            "desc": "Highly empathetic and conversational personal AI designed for supportive dialogue.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "DeepL Write",
            "url": "deepl.com/write",
            "output": "Text",
            "desc": "AI writing assistant that improves phrasing, tone, and grammar in multiple languages.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        }
];
// ─── Coding Agents ────────────────────────────────────────────────────────────
const codingAgents = [
        {
            "name": "GitHub Copilot",
            "url": "github.com/features/copilot",
            "output": "IDE / CLI",
            "desc": "Most widely adopted; embedded in VS Code, JetBrains, Neovim; Copilot Workspace for autonomous multi-file edits.",
            "free": 0,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Cursor",
            "url": "cursor.com",
            "output": "IDE",
            "desc": "AI-first VS Code fork; agent mode autonomously edits multiple files; deep codebase-aware context.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Devin",
            "url": "cognition.ai",
            "output": "Web / API",
            "desc": "Fully autonomous software engineering agent; plans, codes, tests, and deploys independently with minimal input.",
            "free": 0,
            "credits": 0,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 1,
        },
        {
            "name": "Windsurf",
            "url": "codeium.com/windsurf",
            "output": "IDE",
            "desc": "Codeium's agentic IDE; Cascade agent with deep codebase understanding; generous free tier.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Amazon Q Developer",
            "url": "aws.amazon.com/q/developer",
            "output": "IDE / CLI",
            "desc": "AWS-native coding agent; deep cloud integration; security scanning; strong free tier.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Replit AI",
            "url": "replit.com",
            "output": "Web IDE",
            "desc": "Browser-based AI coding with instant cloud deployment; full-stack agent; no local setup required.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 1,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "v0.dev",
            "url": "v0.dev",
            "output": "Web / Code",
            "desc": "Vercel's UI generation agent; prompt-to-React components with live preview and one-click deploy.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Bolt.new",
            "url": "bolt.new",
            "output": "Web IDE",
            "desc": "StackBlitz full-stack coding agent; prompt-to-app entirely in the browser; instant preview and deploy.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Lovable",
            "url": "lovable.dev",
            "output": "Web / Deploy",
            "desc": "Natural language to full-stack app; React + Supabase backend; designed for non-technical founders.",
            "free": 0,
            "credits": 1,
            "sub": 1,
            "api": 0,
            "local": 0,
            "nsfw": 0,
            "tier": 2,
        },
        {
            "name": "Tabnine",
            "url": "tabnine.com",
            "output": "IDE Plugin",
            "desc": "Privacy-first; local model option ensures no code leaves your machine; enterprise self-hosting available.",
            "free": 1,
            "credits": 0,
            "sub": 1,
            "api": 0,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Continue.dev",
            "url": "continue.dev",
            "output": "IDE Plugin",
            "desc": "Open-source IDE extension; connect any local (Ollama) or remote model; fully customizable config.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 1,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
        {
            "name": "Aider",
            "url": "aider.chat",
            "output": "CLI",
            "desc": "Open-source terminal coding agent; works with any LLM API; git-aware with automatic commit messages.",
            "free": 1,
            "credits": 0,
            "sub": 0,
            "api": 1,
            "local": 1,
            "nsfw": 0,
            "tier": 3,
        },
];

// ─── Merged: Web Chat + Coding Agents ────────────────────────────────────────
const webChat = [...webChatAndCoding, ...codingAgents];

// ─── Assembled data object (consumed by code.js) ──────────────────────────────
const data = {
    "speech-and-narration": speechAndNarration,
    "image-analysis":       imageAnalysis,
    "text-image-to-video":  textImageToVideo,
    "text-to-image":        textToImage,
    "text-to-music":        textToMusic,
    "web-chat-coding":      webChat,
};
